//
//  StyleKit.h
//  Example
//
//  Created by  on 10.8.2015.
//  Copyright (c) 2015 PixelCut. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface StyleKit : NSObject

// iOS Controls Customization Outlets
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* blueRectTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* storeTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* soupTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* tabBarBackgroundTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* selectionIndicatorTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* shadowImageTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* projectIconTargets;

// Drawing Methods
+ (void)drawBlueRect;
+ (void)drawBlueRectFramedWithFrame: (CGRect)frame;
+ (void)drawBagWithBagColor: (UIColor*)bagColor;
+ (void)drawLiveButtonWithLiveButtonColor: (UIColor*)liveButtonColor radius: (CGFloat)radius strokeWidth: (CGFloat)strokeWidth;
+ (void)drawClockWithWatchColor: (UIColor*)watchColor hrs: (CGFloat)hrs mins: (CGFloat)mins secs: (CGFloat)secs;
+ (void)drawApertureWithApertureValue: (CGFloat)apertureValue;

// Generated Images
+ (UIImage*)imageOfBlueRect;
+ (UIImage*)imageOfBlueRectFramedWithFrame: (CGRect)frame;
+ (UIImage*)imageOfStore;
+ (UIImage*)imageOfSoup;
+ (UIImage*)imageOfTabBarBackground;
+ (UIImage*)imageOfSelectionIndicator;
+ (UIImage*)imageOfShadowImage;
+ (UIImage*)imageOfButtonWithSelected: (BOOL)selected highlighted: (BOOL)highlighted;
+ (UIImage*)imageOfBagWithBagColor: (UIColor*)bagColor;
+ (UIImage*)imageOfProjectIcon;

@end
